# Generated by Django 4.1.2 on 2023-02-04 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aadhaarDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('AadhaarNum', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('DOB', models.DateField()),
                ('Mobile', models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('Age', models.IntegerField(default=None)),
                ('Gender', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=20)),
                ('Nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='registeredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('username', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('mobile_verified', models.BooleanField(default=False)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('inVotersList', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Election_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='VotingApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=20)),
                ('candidate_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='VotingApp/static/media/candidates')),
                ('agenda', models.CharField(default='', max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingApp.election_category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingApp.status')),
            ],
        ),
    ]
